name: PHP Compatibility Checks

on:
  pull_request:

jobs:
  php8-compatibility:
    name: PHP 7.4- Compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP Compatibility
        uses: pantheon-systems/phpcompatibility-action@dev
        with:
          test-versions: 7.4-
          paths: ${{ github.workspace }}/*.php ${{ github.workspace }}/app/*.php ${{ github.workspace }}/admin/templates/partials/*.php
